const etapas=["pesagem","valores","vendedor","comprador","relatorio"];
const nomes={pesagem:"PESAGEM",valores:"VALORES",vendedor:"VENDEDOR",comprador:"COMPRADOR",relatorio:"RELATÓRIO"};
const LOGO_URL="https://raw.githubusercontent.com/marcioespindolamge-star/caderno-campo/main/assets/logo-paineira.png";
let etapa=0;
let estado=JSON.parse(localStorage.getItem("controlePeso")||"null")||{animais:[],rascunho:{brinco:"",peso:"",descricao:""},valorKg:"",fundo:1.5,vendedor:{nome:"",cpf:"",banco:"",agencia:"",conta:"",email:""},comprador:{nome:"",documento:"",cep:"",cidade:"",endereco:""}};
if(!estado.rascunho) estado.rascunho={brinco:"",peso:"",descricao:""};
if(!Array.isArray(estado.animais)) estado.animais=[];
estado.animais=estado.animais.filter(a=>String(a.brinco||"").trim()||num(a.peso)>0||String(a.descricao||"").trim());
const $=s=>document.querySelector(s);const salvar=()=>localStorage.setItem("controlePeso",JSON.stringify(estado));const moeda=v=>(Number(v)||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});const num=v=>Number(String(v).replace(",","."))||0;
function totais(){const peso=estado.animais.reduce((s,a)=>s+num(a.peso),0),q=estado.animais.length,bruto=peso*num(estado.valorKg),fr=bruto*num(estado.fundo)/100;return{q,peso,media:q?peso/q:0,bruto,fr,liquido:bruto-fr}}
function nav(){$("#passos").innerHTML=etapas.map((e,i)=>`<button class="${i===etapa?"ativo":""}" onclick="ir(${i})">${i+1}. ${nomes[e]}</button>`).join("");etapas.forEach((e,i)=>$("#"+e).classList.toggle("hidden",i!==etapa))}
function ir(i){etapa=Math.max(0,Math.min(i,etapas.length-1));render();window.scrollTo({top:0,behavior:"smooth"})}
function cancelar(){if(confirm("Cancelar esta operação e limpar todos os dados?")){localStorage.removeItem("controlePeso");location.reload()}}
function rodape(prev,next){return `<div class="acoes no-print">${prev?`<button class="btn secundario" onclick="ir(${etapa-1})">← VOLTAR</button>`:""}<button class="btn outline" onclick="cancelar()">CANCELAR</button><div class="direita">${next?`<button class="btn primario" onclick="ir(${etapa+1})">AVANÇAR →</button>`:""}</div></div>`}
function bind(){document.querySelectorAll("[data-model]").forEach(el=>el.oninput=()=>{const p=el.dataset.model.split(".");if(p.length===1)estado[p[0]]=el.value;else estado[p[0]][p[1]]=el.value;salvar();if(etapas[etapa]==="valores")renderValores()})}
function renderPesagem(){const t=totais(),r=estado.rascunho;$("#pesagem").innerHTML=`<h2>PESAGEM DOS ANIMAIS</h2><div class="card-animal entrada-animal"><div class="linha-animal"><div class="campo"><label>Brinco</label><input id="novoBrinco" value="${r.brinco||""}" oninput="rascunho('brinco',this.value)"></div><div class="campo"><label>Peso (kg)</label><input id="novoPeso" inputmode="decimal" value="${r.peso||""}" oninput="rascunho('peso',this.value)"></div><div class="campo desc"><label>Descrição</label><input id="novaDescricao" value="${r.descricao||""}" oninput="rascunho('descricao',this.value)"></div></div><button class="btn primario no-print" onclick="adicionarAnimal()">+ ADICIONAR ANIMAL</button></div>${estado.animais.length?`<div class="lista-adicionados"><h3>ANIMAIS ADICIONADOS</h3>${estado.animais.map((a,i)=>`<div class="animal-adicionado"><div><b>${i+1}. Brinco ${a.brinco}</b><span>${num(a.peso).toFixed(1)} kg${a.descricao?` · ${a.descricao}`:""}</span></div><button class="btn perigo no-print" onclick="excluirAnimal('${a.id}')">EXCLUIR</button></div>`).join("")}</div>`:""}<div class="resumo">Animais adicionados: <strong>${t.q}</strong> &nbsp; Peso total: <strong>${t.peso.toFixed(1)} kg</strong></div>${rodape(false,true)}`}
window.rascunho=(c,v)=>{estado.rascunho[c]=v;salvar()};
window.adicionarAnimal=()=>{const r=estado.rascunho;if(!String(r.brinco).trim()&&!String(r.peso).trim()){alert("Informe o brinco e o peso do animal.");return}if(!String(r.brinco).trim()){alert("Informe o brinco do animal.");return}if(!String(r.peso).trim()||num(r.peso)<=0){alert("Informe um peso válido.");return}estado.animais.push({id:crypto.randomUUID(),brinco:String(r.brinco).trim(),peso:r.peso,descricao:String(r.descricao||"").trim()});estado.rascunho={brinco:"",peso:"",descricao:""};salvar();renderPesagem();setTimeout(()=>document.querySelector("#novoBrinco")?.focus(),0)};
window.excluirAnimal=id=>{if(confirm("Excluir este animal da pesagem?")){estado.animais=estado.animais.filter(a=>a.id!==id);salvar();renderPesagem()}};
function renderValores(){const t=totais();$("#valores").innerHTML=`<h2>VALORES</h2><div class="grid"><div class="campo"><label>Valor por kg (R$)</label><input data-model="valorKg" inputmode="decimal" value="${estado.valorKg}"></div><div class="campo"><label>Fundo Rural (%)</label><input data-model="fundo" inputmode="decimal" value="${estado.fundo}"></div></div><div class="resumo"><div>Peso total: <b>${t.peso.toFixed(1)} kg</b></div><div>Peso médio: <b>${t.media.toFixed(1)} kg</b></div><div>Valor bruto: <b>${moeda(t.bruto)}</b></div><div>Fundo Rural (${num(estado.fundo).toFixed(2)}%): <b>${moeda(t.fr)}</b></div><div>Valor líquido: <strong>${moeda(t.liquido)}</strong></div></div>${rodape(true,true)}`;bind()}
function camposPessoa(tipo){const p=estado[tipo],comprador=tipo==="comprador";return `<div class="grid"><div class="campo full"><label>Nome</label><input data-model="${tipo}.nome" value="${p.nome}"></div><div class="campo"><label>${comprador?"CPF / CNPJ":"CPF"}</label><input data-model="${tipo}.${comprador?"documento":"cpf"}" value="${comprador?p.documento:p.cpf}"></div>${comprador?`<div class="campo"><label>CEP</label><input id="cep" data-model="comprador.cep" inputmode="numeric" value="${p.cep}" onblur="buscarCep()"></div><div class="campo"><label>Cidade</label><input data-model="comprador.cidade" value="${p.cidade}"></div><div class="campo full"><label>Endereço</label><input data-model="comprador.endereco" value="${p.endereco}"></div>`:`<div class="campo"><label>Banco</label><input data-model="vendedor.banco" value="${p.banco}"></div><div class="campo"><label>Agência</label><input data-model="vendedor.agencia" value="${p.agencia}"></div><div class="campo"><label>Conta</label><input data-model="vendedor.conta" value="${p.conta}"></div><div class="campo full"><label>E-mail <span style="font-weight:normal">(opcional)</span></label><input type="email" data-model="vendedor.email" value="${p.email}"></div>`}</div>`}
window.buscarCep=async()=>{const cep=estado.comprador.cep.replace(/\D/g,"");if(cep.length!==8)return;try{const r=await fetch(`https://viacep.com.br/ws/${cep}/json/`),d=await r.json();if(!d.erro){estado.comprador.cidade=`${d.localidade||""}${d.uf?` - ${d.uf}`:""}`;estado.comprador.endereco=[d.logradouro,d.bairro].filter(Boolean).join(" - ");salvar();renderComprador()}}catch(e){}};
function renderVendedor(){$("#vendedor").innerHTML=`<h2>VENDEDOR</h2>${camposPessoa("vendedor")}${rodape(true,true)}`;bind()}function renderComprador(){$("#comprador").innerHTML=`<h2>COMPRADOR</h2>${camposPessoa("comprador")}<p class="aviso">Ao informar um CEP válido, cidade e endereço são preenchidos automaticamente e podem ser alterados.</p>${rodape(true,true)}`;bind()}
function renderRelatorio(){const t=totais(),v=estado.vendedor,c=estado.comprador;$("#relatorio").innerHTML=`<div class="report-header"><img src="${LOGO_URL}" class="logo"><div><h2 style="margin:0">AGROPECUÁRIA PAINEIRA</h2><b>RELATÓRIO DE PESAGEM E VENDA</b></div></div><div class="bloco"><h3>DADOS DO VENDEDOR</h3><div><b>${v.nome||"-"}</b> — CPF: ${v.cpf||"-"}</div><div>Banco: ${v.banco||"-"} &nbsp; Agência: ${v.agencia||"-"} &nbsp; Conta: ${v.conta||"-"}</div>${v.email?`<div>E-mail: ${v.email}</div>`:""}</div><div class="bloco"><h3>DADOS DO COMPRADOR</h3><div><b>${c.nome||"-"}</b> — CPF/CNPJ: ${c.documento||"-"}</div><div>${c.endereco||"-"}${c.cidade?` — ${c.cidade}`:""}${c.cep?` — CEP ${c.cep}`:""}</div></div><div class="bloco"><h3>ANIMAIS</h3><table class="tabela"><thead><tr><th>Brinco</th><th>Peso (kg)</th><th>Descrição</th><th>Valor/kg</th><th>Total</th></tr></thead><tbody>${estado.animais.map(a=>`<tr><td>${a.brinco||"-"}</td><td class="right">${num(a.peso).toFixed(1)}</td><td>${a.descricao||"-"}</td><td class="right">${moeda(estado.valorKg)}</td><td class="right">${moeda(num(a.peso)*num(estado.valorKg))}</td></tr>`).join("")}</tbody></table></div><div class="bloco"><h3>RESUMO</h3><table class="tabela"><tbody><tr><td>Quantidade</td><td class="right">${t.q}</td></tr><tr><td>Peso total</td><td class="right">${t.peso.toFixed(1)} kg</td></tr><tr><td>Peso médio</td><td class="right">${t.media.toFixed(1)} kg</td></tr><tr><td>Valor bruto</td><td class="right">${moeda(t.bruto)}</td></tr><tr><td>Fundo Rural (${num(estado.fundo).toFixed(2)}%)</td><td class="right">- ${moeda(t.fr)}</td></tr><tr><td><b>VALOR LÍQUIDO</b></td><td class="right"><b>${moeda(t.liquido)}</b></td></tr></tbody></table></div><div class="acoes no-print"><button class="btn secundario" onclick="ir(3)">← VOLTAR</button><button class="btn outline" onclick="cancelar()">CANCELAR</button><div class="direita"><button class="btn primario" onclick="window.print()">🖨 IMPRIMIR</button></div></div>`}
function render(){nav();renderPesagem();renderValores();renderVendedor();renderComprador();renderRelatorio();nav()}render();