const etapas=["pesagem","valores","vendedor","comprador","relatorio"];
const nomes={pesagem:"PESAGEM",valores:"VALORES",vendedor:"VENDEDOR",comprador:"COMPRADOR",relatorio:"RELATÓRIO"};
const LOGO_URL="assets/logo-paineira.jpg?v=20260909-0920";
const $=s=>document.querySelector(s), num=v=>Number(String(v).replace(",","."))||0, moeda=v=>(Number(v)||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
let etapa=0;
let estado=JSON.parse(localStorage.getItem("controlePeso")||"null")||{};
estado.animais=Array.isArray(estado.animais)?estado.animais:[]; estado.rascunho=estado.rascunho||{brinco:"",peso:"",descricao:""}; estado.valorKg=estado.valorKg||""; estado.fundo=estado.fundo??1.5;
estado.vendedor={nome:"",cpf:"",banco:"",agencia:"",conta:"",email:"",...(estado.vendedor||{})};
const antigoDoc=estado.comprador?.documento||""; estado.comprador={nome:"",cpf:"",cnpj:"",cep:"",cidade:"",estado:"",endereco:"",...(estado.comprador||{})}; if(antigoDoc&&!estado.comprador.cpf&&!estado.comprador.cnpj){const d=antigoDoc.replace(/\D/g,""); if(d.length===11)estado.comprador.cpf=antigoDoc; if(d.length===14)estado.comprador.cnpj=antigoDoc}
const salvar=()=>localStorage.setItem("controlePeso",JSON.stringify(estado)); salvar();
function cpfMask(v){let d=String(v).replace(/\D/g,"").slice(0,11);return d.replace(/(\d{3})(\d)/,"$1.$2").replace(/(\d{3})(\d)/,"$1.$2").replace(/(\d{3})(\d{1,2})$/,"$1-$2")}
function cnpjMask(v){let d=String(v).replace(/\D/g,"").slice(0,14);return d.replace(/^(\d{2})(\d)/,"$1.$2").replace(/^(\d{2})\.(\d{3})(\d)/,"$1.$2.$3").replace(/\.(\d{3})(\d)/,".$1/$2").replace(/(\d{4})(\d)/,"$1-$2")}
function cepMask(v){let d=String(v).replace(/\D/g,"").slice(0,8);return d.length>5?d.slice(0,5)+"-"+d.slice(5):d}
function totais(){const peso=estado.animais.reduce((s,a)=>s+num(a.peso),0),q=estado.animais.length,bruto=peso*num(estado.valorKg),fr=bruto*num(estado.fundo)/100;return{q,peso,media:q?peso/q:0,bruto,fr,liquido:bruto-fr}}
function nav(){$("#passos").innerHTML=etapas.map((e,i)=>`<button class="${i===etapa?"ativo":""}" onclick="ir(${i})">${nomes[e]}</button>`).join("");etapas.forEach((e,i)=>$("#"+e).classList.toggle("hidden",i!==etapa))}
function ir(i){etapa=Math.max(0,Math.min(i,4));render();window.scrollTo({top:0,behavior:"smooth"})}
function cancelar(){if(confirm("Cancelar esta operação e limpar todos os dados?")){localStorage.removeItem("controlePeso");location.reload()}}
function rodape(prev,next){const mostraCancelar=etapa===0;return `<div class="acoes no-print">${prev?`<button class="btn secundario" onclick="ir(${etapa-1})">← VOLTAR</button>`:""}${mostraCancelar?`<button class="btn outline" onclick="cancelar()">CANCELAR</button>`:""}<div class="direita">${next?`<button class="btn primario" onclick="ir(${etapa+1})">AVANÇAR →</button>`:""}</div></div>`}
function bind(){document.querySelectorAll("[data-model]").forEach(el=>el.oninput=()=>{const p=el.dataset.model.split(".");let v=el.value;if(el.dataset.mask==="cpf")v=cpfMask(v);if(el.dataset.mask==="cnpj")v=cnpjMask(v);if(el.dataset.mask==="cep")v=cepMask(v);el.value=v;p.length===1?estado[p[0]]=v:estado[p[0]][p[1]]=v;salvar();if(el.dataset.mask==="cep"&&v.replace(/\D/g,"").length===8)buscarCep();if(etapa===1)atualizarResumoValores()})}
function renderPesagem(){const t=totais(),r=estado.rascunho;$("#pesagem").innerHTML=`<h2>PESAGEM DOS ANIMAIS</h2><div class="card-animal"><div class="linha-animal"><div class="campo"><label>Brinco</label><input id="novoBrinco" value="${r.brinco||""}" oninput="rascunho('brinco',this.value)"></div><div class="campo"><label>Peso (kg)</label><input id="novoPeso" inputmode="decimal" value="${r.peso||""}" oninput="rascunho('peso',this.value)"></div><div class="campo desc"><label>Descrição</label><input value="${r.descricao||""}" oninput="rascunho('descricao',this.value)"></div></div><button class="btn primario no-print" onclick="adicionarAnimal()">+ ADICIONAR ANIMAL</button></div>${estado.animais.length?`<div class="lista-adicionados"><h3>ANIMAIS ADICIONADOS</h3>${estado.animais.map((a,i)=>`<div class="animal-adicionado"><div><b>${i+1}. Brinco ${a.brinco}</b><span>${num(a.peso).toFixed(1)} kg${a.descricao?` · ${a.descricao}`:""}</span></div><button class="btn perigo" onclick="excluirAnimal('${a.id}')">EXCLUIR</button></div>`).join("")}</div>`:""}<div class="resumo">Animais adicionados: <strong>${t.q}</strong> &nbsp; Peso total: <strong>${t.peso.toFixed(1)} kg</strong></div>${rodape(false,true)}`}
window.rascunho=(c,v)=>{estado.rascunho[c]=v;salvar()};window.adicionarAnimal=()=>{const r=estado.rascunho;if(!String(r.brinco).trim()||num(r.peso)<=0){alert("Informe o brinco e um peso válido.");return}estado.animais.push({id:crypto.randomUUID(),brinco:String(r.brinco).trim(),peso:r.peso,descricao:String(r.descricao||"").trim()});estado.rascunho={brinco:"",peso:"",descricao:""};salvar();renderPesagem()};window.excluirAnimal=id=>{if(confirm("Excluir este animal?")){estado.animais=estado.animais.filter(a=>a.id!==id);salvar();renderPesagem()}};
function atualizarResumoValores(){const t=totais();const dados={pesoTotal:`${t.peso.toFixed(1)} kg`,pesoMedio:`${t.media.toFixed(1)} kg`,valorBruto:moeda(t.bruto),fundoRural:moeda(t.fr),valorLiquido:moeda(t.liquido)};Object.entries(dados).forEach(([id,valor])=>{const el=document.getElementById(id);if(el)el.textContent=valor})}
function renderValores(){const t=totais();$("#valores").innerHTML=`<h2>VALORES</h2><div class="grid"><div class="campo"><label>Valor por kg (R$)</label><input data-model="valorKg" inputmode="decimal" value="${estado.valorKg}"></div><div class="campo"><label>Fundo Rural (%)</label><input data-model="fundo" inputmode="decimal" value="${estado.fundo}"></div></div><div class="resumo-valores"><div class="resumo-valores-titulo"><span>▥</span> RESUMO DA PESAGEM</div><div class="metricas"><div class="metrica verde"><div class="icone">⚖️</div><span>PESO TOTAL</span><strong id="pesoTotal">${t.peso.toFixed(1)} kg</strong></div><div class="metrica azul"><div class="icone">📊</div><span>PESO MÉDIO</span><strong id="pesoMedio">${t.media.toFixed(1)} kg</strong></div><div class="metrica amarelo"><div class="icone">🪙</div><span>VALOR BRUTO</span><strong id="valorBruto">${moeda(t.bruto)}</strong></div><div class="metrica vermelho"><div class="icone">%</div><span>FUNDO RURAL</span><strong id="fundoRural">${moeda(t.fr)}</strong></div><div class="metrica verde"><div class="icone">💰</div><span>VALOR LÍQUIDO</span><strong id="valorLiquido">${moeda(t.liquido)}</strong></div></div></div>${rodape(true,true)}`;bind()}
function renderVendedor(){const v=estado.vendedor;$("#vendedor").innerHTML=`<h2>VENDEDOR</h2><div class="grid"><div class="campo full"><label>Nome</label><input data-model="vendedor.nome" value="${v.nome}"></div><div class="campo"><label>CPF</label><input data-model="vendedor.cpf" data-mask="cpf" inputmode="numeric" maxlength="14" value="${cpfMask(v.cpf)}"></div><div class="campo full" style="display:grid;grid-template-columns:minmax(120px,1.5fr) minmax(80px,.75fr) minmax(90px,.9fr);gap:12px"><div class="campo"><label>Banco</label><input data-model="vendedor.banco" value="${v.banco}"></div><div class="campo"><label>Agência</label><input data-model="vendedor.agencia" value="${v.agencia}"></div><div class="campo"><label>C/C</label><input data-model="vendedor.conta" value="${v.conta}"></div></div><div class="campo full"><label>E-mail (opcional)</label><input data-model="vendedor.email" value="${v.email}"></div></div>${rodape(true,true)}`;bind()}
function renderComprador(){const c=estado.comprador;$("#comprador").innerHTML=`<h2>COMPRADOR</h2><div class="grid"><div class="campo full"><label>Nome</label><input data-model="comprador.nome" value="${c.nome}"></div><div class="campo"><label>CPF</label><input data-model="comprador.cpf" data-mask="cpf" inputmode="numeric" maxlength="14" value="${cpfMask(c.cpf)}"></div><div class="campo"><label>CNPJ</label><input data-model="comprador.cnpj" data-mask="cnpj" inputmode="numeric" maxlength="18" value="${cnpjMask(c.cnpj)}"></div><div class="campo full" style="display:grid;grid-template-columns:minmax(85px,.75fr) minmax(105px,2fr) minmax(58px,.55fr);gap:10px"><div class="campo"><label>CEP</label><input data-model="comprador.cep" data-mask="cep" type="text" inputmode="numeric" maxlength="9" placeholder="00000-000" value="${cepMask(c.cep)}" onblur="buscarCep()"></div><div class="campo"><label>Cidade</label><input data-model="comprador.cidade" value="${c.cidade}"></div><div class="campo"><label>Estado</label><input data-model="comprador.estado" maxlength="2" value="${c.estado}"></div></div><div class="campo full"><label>Endereço</label><input data-model="comprador.endereco" value="${c.endereco}"></div></div>${rodape(true,true)}`;bind()}
window.buscarCep=async()=>{const cep=String(estado.comprador.cep).replace(/\D/g,"");if(cep.length!==8)return;try{const d=await(await fetch(`https://viacep.com.br/ws/${cep}/json/`)).json();if(!d.erro){estado.comprador.cep=cepMask(cep);estado.comprador.cidade=d.localidade||"";estado.comprador.estado=d.uf||"";estado.comprador.endereco=[d.logradouro,d.bairro].filter(Boolean).join(" - ");salvar();renderComprador()}}catch(e){}};
window.imprimirRelatorio=()=>window.print();
function renderRelatorio(){const t=totais(),v=estado.vendedor,c=estado.comprador,doc=c.cpf?`CPF: ${cpfMask(c.cpf)}`:(c.cnpj?`CNPJ: ${cnpjMask(c.cnpj)}`:"Documento: -");$("#relatorio").innerHTML=`<div class="report-header"><img src="${LOGO_URL}" class="logo"><div><h2>AGROPECUÁRIA PAINEIRA</h2><b>RELATÓRIO DE PESAGEM E VENDA</b></div></div><div class="bloco"><h3>DADOS DO VENDEDOR</h3><b>${v.nome||"-"}</b> — CPF: ${v.cpf?cpfMask(v.cpf):"-"}<div>Banco: ${v.banco||"-"} &nbsp; Agência: ${v.agencia||"-"} &nbsp; C/C: ${v.conta||"-"}</div></div><div class="bloco"><h3>DADOS DO COMPRADOR</h3><b>${c.nome||"-"}</b> — ${doc}<div>${c.endereco||"-"}${c.cidade?` — ${c.cidade}`:""}${c.estado?`/${c.estado}`:""}${c.cep?` — CEP ${cepMask(c.cep)}`:""}</div></div><div class="bloco"><h3>ANIMAIS</h3><table class="tabela"><thead><tr><th>Brinco</th><th>Peso</th><th>Descrição</th><th>Valor/kg</th><th>Total</th></tr></thead><tbody>${estado.animais.map(a=>`<tr><td>${a.brinco}</td><td>${num(a.peso).toFixed(1)} kg</td><td>${a.descricao||"-"}</td><td>${moeda(estado.valorKg)}</td><td>${moeda(num(a.peso)*num(estado.valorKg))}</td></tr>`).join("")}</tbody></table></div><div class="bloco"><h3>RESUMO</h3><table class="tabela"><tbody><tr><td>Quantidade</td><td>${t.q}</td></tr><tr><td>Peso total</td><td>${t.peso.toFixed(1)} kg</td></tr><tr><td>Peso médio</td><td>${t.media.toFixed(1)} kg</td></tr><tr><td>Valor bruto</td><td>${moeda(t.bruto)}</td></tr><tr><td>Fundo Rural (${num(estado.fundo).toFixed(2)}%)</td><td>- ${moeda(t.fr)}</td></tr><tr><td><b>VALOR LÍQUIDO</b></td><td><b>${moeda(t.liquido)}</b></td></tr></tbody></table></div><div class="acoes no-print"><button class="btn secundario" onclick="ir(3)">← VOLTAR</button><button class="btn primario" onclick="window.print()" aria-label="Imprimir" title="Imprimir" style="font-size:26px;padding:8px 22px">🖨️</button><button class="btn outline" onclick="cancelar()">CANCELAR</button></div>`}
function render(){renderPesagem();renderValores();renderVendedor();renderComprador();renderRelatorio();nav()}render();