const etapas=["pesagem","valores","vendedor","comprador","relatorio"];
const LOGO_URL="https://raw.githubusercontent.com/marcioespindolamge-star/caderno-campo/main/assets/logo-paineira.png";
const $=s=>document.querySelector(s);
const num=v=>Number(String(v??"").replace(",","."))||0;
const moeda=v=>(Number(v)||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const soDigitos=v=>String(v||"").replace(/\D/g,"");
const maskCPF=v=>{let d=soDigitos(v).slice(0,11);return d.replace(/(\d{3})(\d)/,"$1.$2").replace(/(\d{3})(\d)/,"$1.$2").replace(/(\d{3})(\d{1,2})$/,"$1-$2")};
const maskCNPJ=v=>{let d=soDigitos(v).slice(0,14);return d.replace(/^(\d{2})(\d)/,"$1.$2").replace(/^(\d{2})\.(\d{3})(\d)/,"$1.$2.$3").replace(/\.(\d{3})(\d)/,".$1/$2").replace(/(\d{4})(\d)/,"$1-$2")};
function cpfValido(v){const d=soDigitos(v);if(d.length!==11||/^(\d)\1{10}$/.test(d))return false;let s=0;for(let i=0;i<9;i++)s+=Number(d[i])*(10-i);let r=(s*10)%11;if(r===10)r=0;if(r!==Number(d[9]))return false;s=0;for(let i=0;i<10;i++)s+=Number(d[i])*(11-i);r=(s*10)%11;if(r===10)r=0;return r===Number(d[10])}
function cnpjValido(v){const d=soDigitos(v);if(d.length!==14||/^(\d)\1{13}$/.test(d))return false;const calc=base=>{let peso=base.length-7,s=0;for(const n of base){s+=Number(n)*peso--;if(peso<2)peso=9}const r=s%11;return r<2?0:11-r};const d1=calc(d.slice(0,12)),d2=calc(d.slice(0,12)+d1);return d.endsWith(`${d1}${d2}`)}
let etapa=0;
let estado=JSON.parse(localStorage.getItem("controlePeso")||"null")||{animais:[],rascunho:{brinco:"",peso:"",descricao:""},valorKg:"",fundo:1.5,vendedor:{nome:"",cpf:"",banco:"",agencia:"",conta:"",email:""},comprador:{nome:"",cpf:"",cnpj:"",cep:"",cidade:"",endereco:""}};
if(!estado.rascunho)estado.rascunho={brinco:"",peso:"",descricao:""};if(!Array.isArray(estado.animais))estado.animais=[];
if(!estado.vendedor)estado.vendedor={};if(!estado.comprador)estado.comprador={};
if(!("cpf" in estado.comprador))estado.comprador.cpf="";if(!("cnpj" in estado.comprador))estado.comprador.cnpj="";
if(estado.comprador.documento&&!estado.comprador.cpf&&!estado.comprador.cnpj){const d=soDigitos(estado.comprador.documento);if(d.length===11)estado.comprador.cpf=maskCPF(d);if(d.length===14)estado.comprador.cnpj=maskCNPJ(d)}
estado.vendedor.cpf=maskCPF(estado.vendedor.cpf||"");estado.comprador.cpf=maskCPF(estado.comprador.cpf||"");estado.comprador.cnpj=maskCNPJ(estado.comprador.cnpj||"");
estado.animais=estado.animais.filter(a=>String(a.brinco||"").trim()||num(a.peso)>0||String(a.descricao||"").trim());
const salvar=()=>localStorage.setItem("controlePeso",JSON.stringify(estado));salvar();
function totais(){const peso=estado.animais.reduce((s,a)=>s+num(a.peso),0),q=estado.animais.length,bruto=peso*num(estado.valorKg),fr=bruto*num(estado.fundo)/100;return{q,peso,media:q?peso/q:0,bruto,fr,liquido:bruto-fr}}
function nav(){const itens=[`<span class="menu-emoji">⚖️</span>`,`<span class="menu-emoji">💰</span>`,`<img class="menu-img" src="menu-vendedor.svg" alt="Vendedor">`,`<img class="menu-img" src="menu-comprador.svg" alt="Comprador">`,`<span class="menu-emoji">📄</span>`];$("#passos").innerHTML=etapas.map((e,i)=>`<button class="${i===etapa?"ativo":""}" onclick="ir(${i})" aria-label="${e}">${itens[i]}</button>`).join("");etapas.forEach((e,i)=>$("#"+e).classList.toggle("hidden",i!==etapa))}
function ir(i){if(i>etapa&&!validarEtapa(etapa))return;etapa=Math.max(0,Math.min(i,etapas.length-1));render();window.scrollTo({top:0,behavior:"smooth"})}
function validarEtapa(i){if(i===2){if(!estado.vendedor.cpf||!cpfValido(estado.vendedor.cpf)){alert("Informe um CPF válido para o vendedor no formato 000.000.000-00.");return false}}if(i===3){const temCpf=soDigitos(estado.comprador.cpf).length>0,temCnpj=soDigitos(estado.comprador.cnpj).length>0;if(!temCpf&&!temCnpj){alert("Informe o CPF ou o CNPJ do comprador. Pelo menos um é obrigatório.");return false}if(temCpf&&!cpfValido(estado.comprador.cpf)){alert("O CPF do comprador é inválido.");return false}if(temCnpj&&!cnpjValido(estado.comprador.cnpj)){alert("O CNPJ do comprador é inválido.");return false}}return true}
function cancelar(){if(confirm("Cancelar esta operação e limpar todos os dados?")){localStorage.removeItem("controlePeso");location.reload()}}
function rodape(prev,next){return `<div class="acoes no-print">${prev?`<button class="btn secundario" onclick="ir(${etapa-1})">← VOLTAR</button>`:""}<button class="btn outline" onclick="cancelar()">CANCELAR</button><div class="direita">${next?`<button class="btn primario" onclick="ir(${etapa+1})">AVANÇAR →</button>`:""}</div></div>`}
function bind(){document.querySelectorAll("[data-model]").forEach(el=>el.oninput=()=>{const p=el.dataset.model.split(".");let v=el.value;if(el.dataset.mask==="cpf")v=maskCPF(v);if(el.dataset.mask==="cnpj")v=maskCNPJ(v);if(v!==el.value)el.value=v;if(p.length===1)estado[p[0]]=v;else estado[p[0]][p[1]]=v;salvar();if(etapas[etapa]==="valores")renderValores()})}
function renderPesagem(){const t=totais(),r=estado.rascunho;$("#pesagem").innerHTML=`<h2>PESAGEM DOS ANIMAIS</h2><div class="card-animal entrada-animal"><div class="linha-animal"><div class="campo"><label>Brinco</label><input id="novoBrinco" value="${r.brinco||""}" oninput="rascunho('brinco',this.value)"></div><div class="campo"><label>Peso (kg)</label><input id="novoPeso" inputmode="decimal" value="${r.peso||""}" oninput="rascunho('peso',this.value)"></div><div class="campo desc"><label>Descrição</label><input id="novaDescricao" value="${r.descricao||""}" oninput="rascunho('descricao',this.value)"></div></div><button class="btn primario no-print" onclick="adicionarAnimal()">+ ADICIONAR ANIMAL</button></div>${estado.animais.length?`<div class="lista-adicionados"><h3>ANIMAIS ADICIONADOS</h3>${estado.animais.map((a,i)=>`<div class="animal-adicionado"><div><b>${i+1}. Brinco ${a.brinco}</b><span>${num(a.peso).toFixed(1)} kg${a.descricao?` · ${a.descricao}`:""}</span></div><button class="btn perigo no-print" onclick="excluirAnimal('${a.id}')">EXCLUIR</button></div>`).join("")}</div>`:""}<div class="resumo">Animais adicionados: <strong>${t.q}</strong> &nbsp; Peso total: <strong>${t.peso.toFixed(1)} kg</strong></div>${rodape(false,true)}`}
window.rascunho=(c,v)=>{estado.rascunho[c]=v;salvar()};window.adicionarAnimal=()=>{const r=estado.rascunho;if(!String(r.brinco).trim()){alert("Informe o brinco do animal.");return}if(!String(r.peso).trim()||num(r.peso)<=0){alert("Informe um peso válido.");return}estado.animais.push({id:crypto.randomUUID(),brinco:String(r.brinco).trim(),peso:r.peso,descricao:String(r.descricao||"").trim()});estado.rascunho={brinco:"",peso:"",descricao:""};salvar();renderPesagem();setTimeout(()=>document.querySelector("#novoBrinco")?.focus(),0)};window.excluirAnimal=id=>{if(confirm("Excluir este animal da pesagem?")){estado.animais=estado.animais.filter(a=>a.id!==id);salvar();renderPesagem()}};
function renderValores(){const t=totais();$("#valores").innerHTML=`<h2>VALORES</h2><div class="grid"><div class="campo"><label>Valor por kg (R$)</label><input data-model="valorKg" inputmode="decimal" value="${estado.valorKg}"></div><div class="campo"><label>Fundo Rural (%)</label><input data-model="fundo" inputmode="decimal" value="${estado.fundo}"></div></div><div class="resumo"><div>Peso total: <b>${t.peso.toFixed(1)} kg</b></div><div>Peso médio: <b>${t.media.toFixed(1)} kg</b></div><div>Valor bruto: <b>${moeda(t.bruto)}</b></div><div>Fundo Rural (${num(estado.fundo).toFixed(2)}%): <b>${moeda(t.fr)}</b></div><div>Valor líquido: <strong>${moeda(t.liquido)}</strong></div></div>${rodape(true,true)}`;bind()}
function renderVendedor(){const p=estado.vendedor;$("#vendedor").innerHTML=`<h2>VENDEDOR</h2><div class="grid"><div class="campo full"><label>Nome</label><input data-model="vendedor.nome" value="${p.nome||""}"></div><div class="campo"><label>CPF</label><input data-model="vendedor.cpf" data-mask="cpf" inputmode="numeric" maxlength="14" placeholder="000.000.000-00" value="${p.cpf||""}"></div><div class="campo"><label>Banco</label><input data-model="vendedor.banco" value="${p.banco||""}"></div><div class="campo"><label>Agência</label><input data-model="vendedor.agencia" value="${p.agencia||""}"></div><div class="campo"><label>Conta</label><input data-model="vendedor.conta" value="${p.conta||""}"></div><div class="campo full"><label>E-mail <span style="font-weight:normal">(opcional)</span></label><input type="email" data-model="vendedor.email" value="${p.email||""}"></div></div><p class="aviso">CPF no formato 000.000.000-00.</p>${rodape(true,true)}`;bind()}
function renderComprador(){const p=estado.comprador;$("#comprador").innerHTML=`<h2>COMPRADOR</h2><div class="grid"><div class="campo full"><label>Nome / Razão Social</label><input data-model="comprador.nome" value="${p.nome||""}"></div><div class="campo"><label>CPF</label><input data-model="comprador.cpf" data-mask="cpf" inputmode="numeric" maxlength="14" placeholder="000.000.000-00" value="${p.cpf||""}"></div><div class="campo"><label>CNPJ</label><input data-model="comprador.cnpj" data-mask="cnpj" inputmode="numeric" maxlength="18" placeholder="00.000.000/0000-00" value="${p.cnpj||""}"></div><div class="campo"><label>CEP</label><input data-model="comprador.cep" inputmode="numeric" value="${p.cep||""}" onblur="buscarCep()"></div><div class="campo"><label>Cidade</label><input data-model="comprador.cidade" value="${p.cidade||""}"></div><div class="campo full"><label>Endereço</label><input data-model="comprador.endereco" value="${p.endereco||""}"></div></div><p class="aviso">Informe CPF ou CNPJ. Pelo menos um é obrigatório.</p>${rodape(true,true)}`;bind()}
window.buscarCep=async()=>{const cep=soDigitos(estado.comprador.cep);if(cep.length!==8)return;try{const r=await fetch(`https://viacep.com.br/ws/${cep}/json/`),d=await r.json();if(!d.erro){estado.comprador.cidade=`${d.localidade||""}${d.uf?` - ${d.uf}`:""}`;estado.comprador.endereco=[d.logradouro,d.bairro].filter(Boolean).join(" - ");salvar();renderComprador()}}catch(e){}};
window.imprimirRelatorio=()=>{try{window.focus();setTimeout(()=>window.print(),50)}catch(e){alert("Não foi possível abrir a impressão neste navegador.")}};
function renderRelatorio(){const t=totais(),v=estado.vendedor,c=estado.comprador;$("#relatorio").innerHTML=`<div class="report-header"><img src="${LOGO_URL}" class="logo"><div><h2 style="margin:0">AGROPECUÁRIA PAINEIRA</h2><b>RELATÓRIO DE PESAGEM E VENDA</b></div></div><div class="bloco"><h3>DADOS DO VENDEDOR</h3><div><b>${v.nome||"-"}</b> — CPF: ${v.cpf||"-"}</div><div>Banco: ${v.banco||"-"} &nbsp; Agência: ${v.agencia||"-"} &nbsp; Conta: ${v.conta||"-"}</div>${v.email?`<div>E-mail: ${v.email}</div>`:""}</div><div class="bloco"><h3>DADOS DO COMPRADOR</h3><div><b>${c.nome||"-"}</b></div><div>CPF: ${c.cpf||"-"} &nbsp; CNPJ: ${c.cnpj||"-"}</div><div>${c.endereco||"-"}${c.cidade?` — ${c.cidade}`:""}${c.cep?` — CEP ${c.cep}`:""}</div></div><div class="bloco"><h3>ANIMAIS</h3><table class="tabela"><thead><tr><th>Brinco</th><th>Peso (kg)</th><th>Descrição</th><th>Valor/kg</th><th>Total</th></tr></thead><tbody>${estado.animais.map(a=>`<tr><td>${a.brinco||"-"}</td><td class="right">${num(a.peso).toFixed(1)}</td><td>${a.descricao||"-"}</td><td class="right">${moeda(estado.valorKg)}</td><td class="right">${moeda(num(a.peso)*num(estado.valorKg))}</td></tr>`).join("")}</tbody></table></div><div class="bloco"><h3>RESUMO</h3><table class="tabela"><tbody><tr><td>Quantidade</td><td class="right">${t.q}</td></tr><tr><td>Peso total</td><td class="right">${t.peso.toFixed(1)} kg</td></tr><tr><td>Peso médio</td><td class="right">${t.media.toFixed(1)} kg</td></tr><tr><td>Valor bruto</td><td class="right">${moeda(t.bruto)}</td></tr><tr><td>Fundo Rural (${num(estado.fundo).toFixed(2)}%)</td><td class="right">- ${moeda(t.fr)}</td></tr><tr><td><b>VALOR LÍQUIDO</b></td><td class="right"><b>${moeda(t.liquido)}</b></td></tr></tbody></table></div><div class="acoes no-print" style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:10px"><button class="btn secundario" onclick="ir(3)">← VOLTAR</button><button class="btn primario" onclick="imprimirRelatorio()">🖨 IMPRIMIR</button><button class="btn outline" onclick="cancelar()">CANCELAR</button></div>`}
function render(){renderPesagem();renderValores();renderVendedor();renderComprador();renderRelatorio();nav()}render();